sudo: false
language: ruby
dist: trusty
before_install:
  - gem update --system --no-rdoc --no-ri
  - gem install bundler --no-rdoc --no-ri
  - gem install jbundler --no-rdoc --no-ri
rvm:
  - jruby-9.2.13.0
jdk:
  - oraclejdk8
script: bundle exec jbundle install && bundle exec rake war && bundle exec rake jardist
notifications:
  email: false
